# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  workflow_dispatch:
    
jobs:
  Deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Replace secret
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: 'Cataclysm_Website.Server/appsettings.json'
      env:
        BattlenetApiClientId: ${{ secrets.BattlenetApiClientId }}
        BattlenetApiClientSecret: ${{ secrets.BattlenetApiClientSecret }}
        TwitchApiClientId: ${{ secrets.TwitchApiClientId }}
        TwitchApiClientSecret: ${{ secrets.TwitchApiClientSecret }}

    - name: Restore dependencies
      run: dotnet restore -r linux-x64
      
    - name: Publish
      run: dotnet publish -c Release --no-restore -r linux-x64 --self-contained true -o "build"
      
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        SOURCE: build/*
        TARGET: /opt/Dragonblight
        SCRIPT_BEFORE: 'export pids=$(pgrep Dragonblight) && if [ $pids ]; then while kill -2 $pids; do sleep 1; done fi;'
        SCRIPT_AFTER: "tmux new -d 'cd /opt/Dragonblight && mv /opt/Dragonblight/Cataclysm_Website.Server /opt/Dragonblight/Dragonblight && chmod +x Dragonblight && ./Dragonblight &> Dragonblight.log'"